#!/usr/bin/env bash
# Script to display numbers from 1 to 20 with special messages at specific iterations.

i=1

while ((i < 21))
do
	echo $i
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((i++))
done

