#!/usr/bin/env bash
# Script to check the existence and properties of the "school" file.

filename=school

if [ -e $filename ];
 then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $filename ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $filename ];
 then
    echo "school is a regular file"
fi

