#!/usr/bin/env bash
# Change the IP resolutions for the following domains:
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

cp /etc/hosts ./tmp_hosts
sed -i /localhost$/d ./tmp_hosts
sed -i /facebook.com$/d ./tmp_hosts
echo -e "127.0.0.2\tlocalhost" >> ./tmp_hosts
echo -e "8.8.8.8\tfacebook.com" >> ./tmp_hosts
cp -f ./tmp_hosts /etc/hosts
rm tmp_hosts
